name: Testing the app
on:
  push: 
jobs:
  Test:
   runs-on: ubuntu-22.04
   steps:
    - uses: actions/checkout@v4
    - name: Installing python
      uses: actions/setup-python@v5
      with:
        Py-version: "3.11"
    - name: Installing dependencies
      run: pip install flask pytest
    - name: Running Test
      run: pytest app.py
 
